import "./globals.css";
import "../style/index.scss";
import AppProvider from "@/contextApi/AppProvider";
import RtlMain from "@/components/rtl/RtlMain";
export const metadata = {
  title: "invenShopfy - Your Inventory Management Tool",
  description: "Generated by InvenShopfy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <AppProvider>
        <html lang="en">
          <head>
            <meta httpEquiv="x-ua-compatible" content="ie=edge" />
            <meta name="description" content="Generated by InvenShopfy" />
            <meta name="robots" content="noindex, follow" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no"
            />
            <link rel="icon" href="/favicon.ico" />
          </head>
          <body suppressHydrationWarning={true}>
            {children}
            <RtlMain />
          </body>
        </html>
      </AppProvider>
    </>
  );
}


